### ISSUE TITLE
Apostrophe display issues

### ISSUE THREAD

**Issue by Tem42** [everything2/everything2#3078] opened 2023-02-14 23:03 UTC
[nicolasstag](https://everything2.com/user/nicolasstag) says ... "I think the old bug with the ' has returned: [https://imgur.com/a/ZA1Tm7A](https://imgur.com/a/ZA1Tm7A) (opera GX browser on windows 10, if that helps)" and "I just tried it on google chrome, same display error"

I am not seeing in Chrome myself, but I am not using Windows.

**Comment by jaybonci** [comment] 2023-10-25 00:36
It's not a separate issue, it's an issue with html entities in the title, so it's the same as the ampersand issue. I just added a test to include for that so all good there.

**Comment by jaybonci** [comment] 2023-10-25 00:36
Duplicate of #3105

**Closed by jaybonci** 2023-10-25 00:36 UTC
