### ISSUE TITLE
Is the Node Backup utility broken?

### ISSUE THREAD

**Issue by Jet-Poop** [everything2/everything2#3108] opened 2023-06-13 01:25 UTC
It's been too long since I did a Node Backup. I was able to get a backup of my drafts, but trying to get a backup of my writeups timed out. 

This may be because I have over 1,500 writeups, and it's too much to get in one go. (If need be, I can do a manual backup.) But I thought I'd check to see if the utility isn't working. 

Thank y'all, I bow before your genius, I cringe at my own ineptitudes.

**Comment by jaybonci** [comment] 2023-10-22 03:21
Hey, I can reproduce the 504 gateway timeout. I'm working on it

**Comment by Jet-Poop** [comment] 2023-10-22 03:28
Don't rush too hard -- I've been doing a manual backup since it gives me a chance to rewrite or revise old writeups or delete stuff that's not good enough to keep. But thank you all the same!  :)

**Comment by jaybonci** [comment] 2023-10-22 04:08
Okay, it appears from the telemetry that the memory is doing something weird due to the Archive::Zip buffering. I'm going to reimplement it in IO::Compress::Zip and try from there.

**Comment by jaybonci** [comment] 2023-10-22 13:36
Hey @Jet-Poop , it's fixed in production. Just testing a few final things on the commit, but it worked for me in admin override mode.

**Closed** 2023-10-22 14:26 UTC

**Comment by Jet-Poop** [comment] 2023-10-22 14:30
Thank you!  :)
